### ISSUE TITLE
Remove CacheLookupScheduler

### ISSUE THREAD

**Issue by chrisstaite-menlo** [allada/turbo-cache#195]
I created CacheLookupScheduler because Goma wasn't getting cache hits.  Turns out this was actually due to #176.  This is now an entirely unused scheduler type.

I thought I'd raise an issue to determine if we want to simply delete it to avoid the maintenance cost.  If I understand the RBE protocol it should actually never be required...

**Comment by allada** [comment]
Actually, the protocol does not require it and I think for more simple clients this is a good feature to have. If anything we may want to document that most clients make the cache lookup pointless.

For example, it would be faster to just skip cache lookups all together on the clients and just execute commands, because the scheduler is almost certainly closer to the cache than the clients. For example tools like `recc` would make more sense to work this way to be able to dispatch commands faster.

**Comment by chrisstaite-menlo** [comment]
So long as you're happy with it being there, I'll leave it in...
